### ISSUE TITLE
Practica de Mockup y Front End

### ISSUE THREAD

**Issue by Edwin-1012** [SistemasTecTlaxiaco/practica-de-mockup-y-front-end-cafe-huerto#2]
[Practica de Mockup y Front-end_Ivan, Alexis, Taoli, Edwin.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-mockup-y-front-end-cafe-huerto/files/6548287/Practica.de.Mockup.y.Front-end_Ivan.Alexis.Taoli.Edwin.pdf)

**Comment by MaGuadalupeQuiroz** [comment]
Calificación: 20%

**Comment by josealfredo79** [comment]
Bien hecho...y revisado
